### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by de-odex** [bung87/amysql#15]
Documentation is sparse and examples do not exist; tests are not commented and such are not suitable as examples. This makes it very difficult to use this library.

**Comment by bung87** [comment]
would u like to create a PR for this? am not a native English speaker, so it's not easy for me

**Comment by de-odex** [comment]
I would like to, except the issue is that I am the one having difficulty learning how to use this library...

I would also be fine with correcting typos and errors in grammar for you if I can understand well enough

**Comment by bung87** [comment]
hi , I've add usage section in readme , feel free create PR for correcting me
